_welcome:
    pattern:  /
    defaults: { _controller: EssensysDemoBundle:Welcome:index }

_demo_secured:
    resource: "@EssensysDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@EssensysDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo