parameters:
#    essensys_core.example.class: Essensys\CoreBundle\Example

services:
#    essensys_core.example:
#        class: %essensys_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
